/**
 * test_model_signature.c -- Ed25519 model signature verification (I-03 / R-02).
 *
 * Part 1: known-answer tests against the embedded verifier using a vector
 *         generated by python cryptography (RFC 8032).
 * Part 2: end-to-end ml_engine tests against the real forest.bin + .sig
 *         (valid loads, tampered model / missing sig / wrong-key sig all
 *         rejected).
 */
#include "unity.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <windows.h>

#include "ed25519_verify.h"
#include "ml_engine.h"

/* ---- Known-answer vector (generated offline by scripts/sign_model.py's
 *      sibling test code; python cryptography Ed25519) ---- */
static const uint8_t KA_PK[32] = {
    0x03, 0xa1, 0x07, 0xbf, 0xf3, 0xce, 0x10, 0xbe, 0x1d, 0x70, 0xdd, 0x18,
    0xe7, 0x4b, 0xc0, 0x99, 0x67, 0xe4, 0xd6, 0x30, 0x9b, 0xa5, 0x0d, 0x5f,
    0x1d, 0xdc, 0x86, 0x64, 0x12, 0x55, 0x31, 0xb8};
static const uint8_t KA_SIG[64] = {
    0xf5, 0x24, 0xd8, 0x4b, 0x1b, 0x52, 0xb6, 0x0f, 0xd5, 0xab, 0x09, 0xe2,
    0xfa, 0x30, 0x6c, 0xd1, 0x54, 0x80, 0xb3, 0x50, 0x15, 0xf9, 0xf6, 0x12,
    0x0b, 0x07, 0x26, 0x47, 0xdc, 0xe6, 0x1d, 0x0f, 0x11, 0xa7, 0x09, 0x65,
    0x3d, 0x34, 0xa7, 0xcb, 0xba, 0xdd, 0x86, 0x94, 0xe8, 0xd8, 0x52, 0x2b,
    0x8d, 0xa5, 0xbc, 0xea, 0x13, 0x1f, 0x70, 0xf0, 0x36, 0x73, 0x75, 0x81,
    0xf4, 0x65, 0xc0, 0x09};
static const uint8_t KA_MSG[46] = {
    0x46, 0x4f, 0x53, 0x2d, 0x41, 0x6e, 0x74, 0x69, 0x76, 0x69, 0x72, 0x75,
    0x73, 0x20, 0x45, 0x64, 0x32, 0x35, 0x35, 0x31, 0x39, 0x20, 0x6b, 0x6e,
    0x6f, 0x77, 0x6e, 0x2d, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x20, 0x74,
    0x65, 0x73, 0x74, 0x20, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72};
static const uint8_t KA_PK_WRONG[32] = {0x42}; /* wrong key (all 0x42) */

static char g_model[MAX_PATH];
static char g_sig[MAX_PATH];
static char g_dir[MAX_PATH];
static const char *ASSETS = "D:\\Experiment\\FOS-Antivirus\\assets\\models";

static void copy_file(const char *src, const char *dst) {
  FILE *f = fopen(src, "rb");
  FILE *g = fopen(dst, "wb");
  TEST_ASSERT_NOT_NULL_MESSAGE(f, "open src");
  TEST_ASSERT_NOT_NULL_MESSAGE(g, "open dst");
  char buf[65536];
  size_t n;
  while ((n = fread(buf, 1, sizeof(buf), f)) > 0) fwrite(buf, 1, n, g);
  fclose(f);
  fclose(g);
}

/* ---------------- Part 1: verifier known-answer ---------------- */

static void test_ka_valid(void) {
  TEST_ASSERT_EQUAL_INT(0, ed25519_verify(KA_SIG, 64, KA_MSG, sizeof(KA_MSG), KA_PK));
}

static void test_ka_tampered_msg(void) {
  uint8_t msg[sizeof(KA_MSG)];
  memcpy(msg, KA_MSG, sizeof(msg));
  msg[0] ^= 0x01;
  TEST_ASSERT_EQUAL_INT(-1, ed25519_verify(KA_SIG, 64, msg, sizeof(msg), KA_PK));
}

static void test_ka_tampered_sig(void) {
  uint8_t sig[64];
  memcpy(sig, KA_SIG, 64);
  sig[7] ^= 0x80;
  TEST_ASSERT_EQUAL_INT(-1, ed25519_verify(sig, 64, KA_MSG, sizeof(KA_MSG), KA_PK));
}

static void test_ka_wrong_key(void) {
  uint8_t wrong[32];
  memset(wrong, 0x42, 32);
  TEST_ASSERT_EQUAL_INT(-1, ed25519_verify(KA_SIG, 64, KA_MSG, sizeof(KA_MSG), wrong));
}

static void test_ka_bad_sizes(void) {
  TEST_ASSERT_EQUAL_INT(-1, ed25519_verify(KA_SIG, 63, KA_MSG, sizeof(KA_MSG), KA_PK));
  TEST_ASSERT_EQUAL_INT(-1, ed25519_verify(KA_SIG, 65, KA_MSG, sizeof(KA_MSG), KA_PK));
  TEST_ASSERT_EQUAL_INT(-1, ed25519_verify(KA_SIG, 64, KA_MSG, 0, KA_PK));
  TEST_ASSERT_EQUAL_INT(-1, ed25519_verify(NULL, 64, KA_MSG, sizeof(KA_MSG), KA_PK));
  TEST_ASSERT_EQUAL_INT(-1, ed25519_verify(KA_SIG, 64, NULL, sizeof(KA_MSG), KA_PK));
  TEST_ASSERT_EQUAL_INT(-1, ed25519_verify(KA_SIG, 64, KA_MSG, sizeof(KA_MSG), NULL));
}

static void test_ka_noncanonical_s(void) {
  /* S + L (the group order) is a non-canonical encoding and must be rejected */
  static const uint8_t L_le[32] = {
      0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7,
      0xa2, 0xde, 0xf9, 0xde, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10};
  uint8_t sig[64];
  unsigned carry = 0;
  memcpy(sig, KA_SIG, 64);
  for (int i = 0; i < 32; i++) {
    unsigned v = sig[32 + i] + L_le[i] + carry;
    sig[32 + i] = (uint8_t)v;
    carry = v >> 8;
  }
  TEST_ASSERT_EQUAL_INT(-1, ed25519_verify(sig, 64, KA_MSG, sizeof(KA_MSG), KA_PK));
}

/* ---------------- Part 2: ml_engine end-to-end ---------------- */

static void test_model_valid_loads(void) {
  copy_file("D:\\Experiment\\FOS-Antivirus\\assets\\models\\forest.bin", g_model);
  copy_file("D:\\Experiment\\FOS-Antivirus\\assets\\models\\forest.bin.sig", g_sig);
  ml_engine_pre_init();
  TEST_ASSERT_EQUAL_INT(0, ml_engine_init(g_model));
  FileFeatures ff;
  memset(&ff, 0, sizeof(ff));
  double score = ml_engine_scan(&ff);
  TEST_ASSERT_NOT_EQUAL(ML_SCORE_ERROR, score);
  ml_engine_cleanup();
}

static void test_model_tampered_rejected(void) {
  copy_file("D:\\Experiment\\FOS-Antivirus\\assets\\models\\forest.bin", g_model);
  copy_file("D:\\Experiment\\FOS-Antivirus\\assets\\models\\forest.bin.sig", g_sig);
  {
    FILE *f = fopen(g_model, "r+b");
    TEST_ASSERT_NOT_NULL(f);
    fseek(f, 64, SEEK_SET);
    unsigned char b = 0;
    fread(&b, 1, 1, f);
    fseek(f, 64, SEEK_SET);
    fwrite(&b, 1, 1, f); /* same byte: only touches header (non-magic) */
    /* flip a byte deep inside the trees */
    fseek(f, 100000, SEEK_SET);
    fread(&b, 1, 1, f);
    fseek(f, 100000, SEEK_SET);
    b ^= 0xFF;
    fwrite(&b, 1, 1, f);
    fclose(f);
  }
  TEST_ASSERT_NOT_EQUAL(0, ml_engine_init(g_model));
  ml_engine_cleanup();
}

static void test_model_missing_sig_rejected(void) {
  copy_file("D:\\Experiment\\FOS-Antivirus\\assets\\models\\forest.bin", g_model);
  DeleteFileA(g_sig);
  TEST_ASSERT_NOT_EQUAL(0, ml_engine_init(g_model));
  ml_engine_cleanup();
}

static void test_model_wrong_key_sig_rejected(void) {
  copy_file("D:\\Experiment\\FOS-Antivirus\\assets\\models\\forest.bin", g_model);
  {
    FILE *f = fopen(g_sig, "wb");
    TEST_ASSERT_NOT_NULL(f);
    fwrite(KA_SIG, 1, 64, f); /* signature over a different message */
    fclose(f);
  }
  TEST_ASSERT_NOT_EQUAL(0, ml_engine_init(g_model));
  ml_engine_cleanup();
}

static void test_model_truncated_sig_rejected(void) {
  copy_file("D:\\Experiment\\FOS-Antivirus\\assets\\models\\forest.bin", g_model);
  {
    FILE *f = fopen(g_sig, "wb");
    TEST_ASSERT_NOT_NULL(f);
    fwrite(KA_SIG, 1, 32, f);
    fclose(f);
  }
  TEST_ASSERT_NOT_EQUAL(0, ml_engine_init(g_model));
  ml_engine_cleanup();
}

static void test_model_valid_again(void) {
  copy_file("D:\\Experiment\\FOS-Antivirus\\assets\\models\\forest.bin", g_model);
  copy_file("D:\\Experiment\\FOS-Antivirus\\assets\\models\\forest.bin.sig", g_sig);
  TEST_ASSERT_EQUAL_INT(0, ml_engine_init(g_model));
  ml_engine_cleanup();
}

void setUp(void) {}
void tearDown(void) {}

int main(void) {
  const char *tmp = getenv("TEMP");
  if (!tmp) tmp = "C:\\Windows\\Temp";
  snprintf(g_dir, sizeof(g_dir), "%s\\fos_sig_test", tmp);
  CreateDirectoryA(g_dir, NULL);
  snprintf(g_model, sizeof(g_model), "%s\\forest.bin", g_dir);
  snprintf(g_sig, sizeof(g_sig), "%s\\forest.bin.sig", g_dir);

  UNITY_BEGIN();
  RUN_TEST(test_ka_valid);
  RUN_TEST(test_ka_tampered_msg);
  RUN_TEST(test_ka_tampered_sig);
  RUN_TEST(test_ka_wrong_key);
  RUN_TEST(test_ka_bad_sizes);
  RUN_TEST(test_ka_noncanonical_s);
  RUN_TEST(test_model_valid_loads);
  RUN_TEST(test_model_tampered_rejected);
  RUN_TEST(test_model_missing_sig_rejected);
  RUN_TEST(test_model_wrong_key_sig_rejected);
  RUN_TEST(test_model_truncated_sig_rejected);
  RUN_TEST(test_model_valid_again);
  return UNITY_END();
}
